trigger: none

pool:  empire_agent_pool

variables:
  WORK_DIR: '$(System.DefaultWorkingDirectory)/environment/dev'
  CONN_SRV: 'empire_service_connection'
  

stages:
  - stage: terraforminit
    jobs:
      - job: terraforminit
        steps:
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: $(WORK_DIR)
            backendServiceArm: $(CONN_SRV)
            backendAzureRmOverrideSubscriptionID: '70d13209-b5da-483b-9f07-a91b9e1a684b'
            backendAzureRmResourceGroupName: 'bappa-state-rg'
            backendAzureRmStorageAccountName: 'mstatefiles'
            backendAzureRmContainerName: 'statefiles'
            backendAzureRmKey: 'project.tfstate'

        - task: TerraformTask@5
          displayName: terraform validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: $(WORK_DIR)

        - task: TerraformTask@5
          displayName: terraform plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: $(WORK_DIR)
            environmentServiceNameAzureRM: $(CONN_SRV)


  - stage: manualvalidation
    dependsOn: terraforminit
    pool: server
    jobs:
      - job: manualvalidation
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'bappakn22@gmail.com'
            approvers: 'bappakn22@gmail.com'
            instructions: 'please approve'

  - stage: terraformdeploy
    dependsOn: manualvalidation
    jobs:
     - job: deployecode
       
       steps:
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: $(WORK_DIR)
            backendServiceArm: $(CONN_SRV)
            backendAzureRmOverrideSubscriptionID: '70d13209-b5da-483b-9f07-a91b9e1a684b'
            backendAzureRmResourceGroupName: 'bappa-state-rg'
            backendAzureRmStorageAccountName: 'mstatefiles'
            backendAzureRmContainerName: 'statefiles'
            backendAzureRmKey: 'project.tfstate'

        - task: TerraformTask@5
          displayName: terraform apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: $(WORK_DIR)
            commandOptions: '-auto-approve'
            environmentServiceNameAzureRM: $(CONN_SRV)