trigger: none

pool:  empire_agent_pool
  

stages:
  - stage: terraforminit
    jobs:
      - job: terraforminit
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            backendServiceArm: 'empire_service_connection'
            backendAzureRmOverrideSubscriptionID: '70d13209-b5da-483b-9f07-a91b9e1a684b'
            backendAzureRmResourceGroupName: 'bappa-state-rg'
            backendAzureRmStorageAccountName: 'mstatefiles'
            backendAzureRmContainerName: 'statefiles'
            backendAzureRmKey: 'project.tftate'